### ISSUE TITLE
about q_logvar_init and p_logvar_init

### ISSUE THREAD

**Issue by ShellingFord221** [kumar-shridhar/PyTorch-BayesianCNN#27]
Hi, in your new code, q_logvar_init and p_logvar_init are parameters in BBBconv2d (in your old code, they have fixed values). What are their initial values? I didn't find them in your code. Thanks!

**Comment by kumar-shridhar** [comment]
Hi @ShellingFord221,

Values are defined inside the Bayesian AlexNet architecture.
![image](https://user-images.githubusercontent.com/20888097/64874544-3b5d2f80-d619-11e9-8508-426e016d6c67.png)

The path is `PyTorch-BayesianCNN/Image `Recognition/utils/BayesianModels/BayesianAlexNet.py`

**Comment by ShellingFord221** [comment]
Hi, in your codes, you define the fixed value of mean and variance of the real distribution of weight, i.e. w_p~N(0, 0.05), and the value of mean and variance of the approximate distribution of weight w_q are parameters (they are initialized by stdv and q_logvar_init). But why are parameters of the real distribution fixed? If we know the real distribution, why should we approximate it by q, rather than just use these values?

**Comment by kumar-shridhar** [comment]
Hi,
We need to define a boundary (or starting point) to contain the distributions in that domain. Otherwise, the distributions might vary a lot and it is hard to make them converge. So we start with something and then use LRT to calculate the change. And we try to learn these both and approximate it. We take a 0 mean and a predefined variance to start with. Variance can be made learnable but 0 mean Normal distribution is a good start to apply LRT efficiently. However, a different distribution can also be used and we can learn the parameters. But it will be way too much to learn considering the complexity of CNNs already and in our experiments, it becomes hard to converge. Hope it makes sense.

**Comment by ShellingFord221** [comment]
Hi, I wonder that will the initial values of p_logvar and q_logvar affect the performance of BCNN? Why or why not? Thanks.

**Comment by ShellingFord221** [comment]
And why do you set the same initial value for real distribution and approximate distribution? Shouldn't they be different? Thanks!

**Comment by kikyo97** [comment]
> 
> 
> Hi, in your codes, you define the fixed value of mean and variance of the real distribution of weight, i.e. w_p~N(0, 0.05), and the value of mean and variance of the approximate distribution of weight w_q are parameters (they are initialized by stdv and q_logvar_init). But why are parameters of the real distribution fixed? If we know the real distribution, why should we approximate it by q, rather than just use these values?

I am also perplexed by this question. In the BBBConv.py, prior_mu and prior_sigma are all fixed. This means that KL Loss will lead to the W_mu and W_sigma to the prior value (i.e., prior_mu and prior_sigma). However, how can we know that the prior value is suitable for our tasks? After all, in the CNN, back propagation can help us optimize the weight.
